#pragma line 1 "mandelbrot-hls/mandelbrot.cpp" ::: 0
#pragma line 1 "mandelbrot-hls/mandelbrot.cpp" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 155 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/Xilinx/Vivado/2017.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 12
#pragma line 156 "/opt/Xilinx/Vivado/2017.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 13
#pragma line 8 "<command line>" 2 ::: 143
#pragma line 1 "<built-in>" 2 ::: 144
#pragma line 1 "mandelbrot-hls/mandelbrot.cpp" 2 ::: 145
#pragma line 1 "mandelbrot-hls/mandelbrot.h" 1 ::: 146
#pragma line 1 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" 1 3 ::: 149
#pragma line 41 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" 3 ::: 150
#pragma line 41 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" 3 ::: 151
#pragma line 1 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++config.h" 1 3 ::: 153
#pragma line 153 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++config.h" 3 ::: 154
#pragma line 393 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++config.h" 3 ::: 164
#pragma line 1 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/os_defines.h" 1 3 ::: 165
#pragma line 40 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/os_defines.h" 3 ::: 166
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 167
#pragma line 345 "/usr/include/features.h" 3 4 ::: 168
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 169
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 170
#pragma line 367 "/usr/include/features.h" 3 4 ::: 171
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 172
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 173
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 174
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 175
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 176
#pragma line 391 "/usr/include/features.h" 3 4 ::: 177
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 178
#pragma line 10 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 3 4 ::: 179
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 180
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 181
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 182
#pragma line 41 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/os_defines.h" 2 3 ::: 183
#pragma line 394 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++config.h" 2 3 ::: 184
#pragma line 1 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/cpu_defines.h" 1 3 ::: 187
#pragma line 397 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++config.h" 2 3 ::: 188
#pragma line 43 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" 2 3 ::: 189
#pragma line 1 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/cpp_type_traits.h" 1 3 ::: 190
#pragma line 36 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/cpp_type_traits.h" 3 ::: 191
#pragma line 36 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/cpp_type_traits.h" 3 ::: 192
#pragma line 68 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/cpp_type_traits.h" 3 ::: 193
#pragma line 198 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/cpp_type_traits.h" 3 ::: 306
#pragma line 422 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/cpp_type_traits.h" 3 ::: 517
#pragma line 44 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" 2 3 ::: 519
#pragma line 1 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ext/type_traits.h" 1 3 ::: 520
#pragma line 33 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ext/type_traits.h" 3 ::: 521
#pragma line 33 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ext/type_traits.h" 3 ::: 522
#pragma line 45 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" 2 3 ::: 702
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 703
#pragma line 28 "/usr/include/math.h" 3 4 ::: 704
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 1 3 4 ::: 709
#pragma line 25 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 3 4 ::: 710
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h" 1 3 4 ::: 711
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 2 3 4 ::: 712
#pragma line 32 "/usr/include/math.h" 2 3 4 ::: 713
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_val.h" 1 3 4 ::: 717
#pragma line 36 "/usr/include/math.h" 2 3 4 ::: 718
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_valf.h" 1 3 4 ::: 720
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 721
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_vall.h" 1 3 4 ::: 722
#pragma line 39 "/usr/include/math.h" 2 3 4 ::: 723
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/inf.h" 1 3 4 ::: 726
#pragma line 42 "/usr/include/math.h" 2 3 4 ::: 727
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/nan.h" 1 3 4 ::: 730
#pragma line 45 "/usr/include/math.h" 2 3 4 ::: 731
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 1 3 4 ::: 735
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 736
#pragma line 49 "/usr/include/math.h" 2 3 4 ::: 739
#pragma line 83 "/usr/include/math.h" 3 4 ::: 740
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 741
#pragma line 54 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 742
#pragma line 153 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 834
#pragma line 178 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 852
#pragma line 204 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 871
#pragma line 375 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1035
#pragma line 84 "/usr/include/math.h" 2 3 4 ::: 1045
#pragma line 104 "/usr/include/math.h" 3 4 ::: 1046
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 1047
#pragma line 54 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1048
#pragma line 153 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1140
#pragma line 178 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1158
#pragma line 204 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1177
#pragma line 375 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1341
#pragma line 105 "/usr/include/math.h" 2 3 4 ::: 1351
#pragma line 151 "/usr/include/math.h" 3 4 ::: 1352
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 1353
#pragma line 54 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1354
#pragma line 153 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1446
#pragma line 178 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1464
#pragma line 204 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1483
#pragma line 375 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1647
#pragma line 152 "/usr/include/math.h" 2 3 4 ::: 1657
#pragma line 168 "/usr/include/math.h" 3 4 ::: 1658
#pragma line 209 "/usr/include/math.h" 3 4 ::: 1660
#pragma line 347 "/usr/include/math.h" 3 4 ::: 1679
#pragma line 370 "/usr/include/math.h" 3 4 ::: 1693
#pragma line 534 "/usr/include/math.h" 3 4 ::: 1708
#pragma line 46 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" 2 3 ::: 1710
#pragma line 76 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" 3 ::: 1711
#pragma line 480 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" 3 ::: 2098
#pragma line 730 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" 3 ::: 2101
#pragma line 4 "mandelbrot-hls/mandelbrot.h" 2 ::: 2215
#pragma line 2 "mandelbrot-hls/mandelbrot.cpp" 2 ::: 2228
