# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /mnt/f/dev/mandelbrot-hls/solution1/impl/verilog/mandlebrot_main.xdc

# IP: ip/mandlebrot_main_ap_sitodp_4_no_dsp_32/mandlebrot_main_ap_sitodp_4_no_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mandlebrot_main_ap_sitodp_4_no_dsp_32 || ORIG_REF_NAME==mandlebrot_main_ap_sitodp_4_no_dsp_32} -quiet] -quiet

# IP: ip/mandlebrot_main_ap_dcmp_0_no_dsp_64/mandlebrot_main_ap_dcmp_0_no_dsp_64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mandlebrot_main_ap_dcmp_0_no_dsp_64 || ORIG_REF_NAME==mandlebrot_main_ap_dcmp_0_no_dsp_64} -quiet] -quiet

# IP: ip/mandlebrot_main_ap_dmul_4_max_dsp_64/mandlebrot_main_ap_dmul_4_max_dsp_64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mandlebrot_main_ap_dmul_4_max_dsp_64 || ORIG_REF_NAME==mandlebrot_main_ap_dmul_4_max_dsp_64} -quiet] -quiet

# IP: ip/mandlebrot_main_ap_dadddsub_3_full_dsp_64/mandlebrot_main_ap_dadddsub_3_full_dsp_64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mandlebrot_main_ap_dadddsub_3_full_dsp_64 || ORIG_REF_NAME==mandlebrot_main_ap_dadddsub_3_full_dsp_64} -quiet] -quiet
