# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /mnt/f/dev/mandelbrot-hls/solution1/impl/verilog/project.cache/wt [current_project]
set_property parent.project_path /mnt/f/dev/mandelbrot-hls/solution1/impl/verilog/project.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /mnt/f/dev/mandelbrot-hls/solution1/impl/verilog/project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /mnt/f/dev/mandelbrot-hls/solution1/impl/verilog/mandlebrot_main.v
  /mnt/f/dev/mandelbrot-hls/solution1/impl/verilog/mandlebrot_main_dbkb.v
  /mnt/f/dev/mandelbrot-hls/solution1/impl/verilog/mandlebrot_main_dcud.v
  /mnt/f/dev/mandelbrot-hls/solution1/impl/verilog/mandlebrot_main_ddEe.v
  /mnt/f/dev/mandelbrot-hls/solution1/impl/verilog/mandlebrot_main_seOg.v
}
read_ip -quiet /mnt/f/dev/mandelbrot-hls/solution1/impl/verilog/project.srcs/sources_1/ip/mandlebrot_main_ap_sitodp_4_no_dsp_32/mandlebrot_main_ap_sitodp_4_no_dsp_32.xci

read_ip -quiet /mnt/f/dev/mandelbrot-hls/solution1/impl/verilog/project.srcs/sources_1/ip/mandlebrot_main_ap_dcmp_0_no_dsp_64/mandlebrot_main_ap_dcmp_0_no_dsp_64.xci

read_ip -quiet /mnt/f/dev/mandelbrot-hls/solution1/impl/verilog/project.srcs/sources_1/ip/mandlebrot_main_ap_dmul_4_max_dsp_64/mandlebrot_main_ap_dmul_4_max_dsp_64.xci

read_ip -quiet /mnt/f/dev/mandelbrot-hls/solution1/impl/verilog/project.srcs/sources_1/ip/mandlebrot_main_ap_dadddsub_3_full_dsp_64/mandlebrot_main_ap_dadddsub_3_full_dsp_64.xci

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /mnt/f/dev/mandelbrot-hls/solution1/impl/verilog/mandlebrot_main.xdc
set_property used_in_implementation false [get_files /mnt/f/dev/mandelbrot-hls/solution1/impl/verilog/mandlebrot_main.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top mandlebrot_main -part xc7z020clg484-1 -no_iobuf -mode out_of_context


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mandlebrot_main.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mandlebrot_main_utilization_synth.rpt -pb mandlebrot_main_utilization_synth.pb"
